name: Cache experiments

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:

  build:

    runs-on: macos-10.15

    env:
      CMAKE_BUILD_TYPE: release
      CMAKE_GENERATOR: "Unix Makefiles"
      CMAKE_BUILD_PARALLEL_LEVEL: 4

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: test-cache
      with:
        path: some.log
        key: ${{ runner.os }}-${{ hashFiles('**/.github/workflows/macosx-experimental.yml') }}
    - name: Generate file
      if: steps.test-cache.outputs.cache-hit != 'true'
      shell: bash
      run: env | tee some.log
    - name: Display file
      shell: bash
      run: cat some.log
